### ISSUE TITLE
Fase 1 - Backend: Configurar servidor ExpressJS

### ISSUE THREAD

**Issue by paulosalvatore** [SalvatoreAcademyEmpresa/gerenciamento-de-tarefas#1]
# Configurar servidor ExpressJS

## Descrição
Configurar o servidor básico utilizando ExpressJS para a aplicação de gerenciamento de tarefas.

## Tarefas
- [x] Inicializar um novo projeto Node.js
- [x] Instalar o ExpressJS
- [x] Configurar o servidor para ouvir em uma porta específica
- [x] Adicionar roteamento básico para a rota raiz
- [x] Testar o servidor para garantir que está funcionando corretamente
- [x] Instalar e configurar nodemon

**Comment by F-K-C** [comment]
Nodemon instalado e projeto inciado
