### ISSUE TITLE
Fase 1 - Backend: Implementar controladores de Tarefas

### ISSUE THREAD

**Issue by paulosalvatore** [SalvatoreAcademyEmpresa/gerenciamento-de-tarefas#5]
# Implementar controladores de Tarefas

## Descrição
Desenvolver os controladores necessários para manipulação das tarefas (CRUD).

## Tarefas
- [x] Criar um controlador para criar novas tarefas
- [x] Criar um controlador para listar todas as tarefas
- [x] Criar um controlador para atualizar uma tarefa existente
- [x] Criar um controlador para deletar uma tarefa
- [x] Testar todos os controladores para garantir que as operações CRUD estão funcionando

**Comment by F-K-C** [comment]
Tarefa realizada!
