### ISSUE TITLE
Fase 1 - Frontend: Implementar componente TaskList com CSS

### ISSUE THREAD

**Issue by paulosalvatore** [SalvatoreAcademyEmpresa/gerenciamento-de-tarefas#7]
# Implementar componente TaskList com CSS

## Descrição
Desenvolver o componente TaskList em ReactJS, incluindo a estilização com CSS.

## Tarefas
- [x] Criar o componente TaskList
- [x] Implementar a lógica para listar todas as tarefas
- [x] Adicionar estilos CSS para o componente
- [x] Testar a exibição da lista de tarefas para garantir que está funcionando e estilizada corretamente

**Comment by alanrochagomes** [comment]
Funcionalidades de gerenciamento de tarefas e edição no componente TodoList/TaskList:

- Implementa estados para gerenciar tarefas, edições e o título da lista
- Adiciona funções para adicionar, remover, editar e alternar a conclusão das tarefas
- Implementa arrastar e soltar para reorganizar tarefas usando react-dnd
- Cria o componente TodoItem para renderizar cada tarefa com suporte para edição inline
- Integra o componente TaskForm para adicionar novas tarefas
- Adiciona funcionalidade para editar o título da lista
- Estiliza e organiza o layout do TodoList/TaskList com CSS
