### ISSUE TITLE
Backend: Implementar o `CORS`

### ISSUE THREAD

**Issue by alanrochagomes** [SalvatoreAcademyEmpresa/gerenciamento-de-tarefas#74]
### **O que precisa ser feito?**

O backend precisa garantir que (a API) inclua os cabeçalhos apropriados. Para isso, é necessário configurar o servidor para permitir requisições, utilizando o pacote cors para facilitar essa configuração.  

**Issue relacionada**

-  #73
-  #71

**Comment by F-K-C** [comment]
Realizei a instalação do CORS no backend. Verifique se agora está funcionando, por favor.
