### ISSUE TITLE
Fase 1 - Frontend: Implementar componente TaskItem com CSS

### ISSUE THREAD

**Issue by paulosalvatore** [SalvatoreAcademyEmpresa/gerenciamento-de-tarefas#8]
# Implementar componente TaskItem com CSS

## Descrição
Desenvolver o componente TaskItem em ReactJS para exibir informações de uma tarefa individual, incluindo a estilização com CSS.

## Tarefas
- [x] Criar o componente TaskItem
- [x] Implementar a lógica para exibir informações de uma tarefa (título, descrição, etc.)
- [x] Adicionar estilos CSS para o componente
- [x] Testar a exibição do componente para garantir que está funcionando e estilizado corretamente

**Comment by alanrochagomes** [comment]
Refatorando o código separando a lógica de exibição das tarefas no componente TaskItem:

- O componente TaskItem para exibir e gerenciar uma tarefa individual
- Move a lógica de exibição e edição das tarefas de TodoList/TaskList para TaskItem
- Atualiza TodoList/TaskList para utilizar o novo componente TaskItem
- Mantém a funcionalidade de arrastar e soltar, edição e alternância de conclusão de tarefas
- Corrige erros de definição de variáveis no TaskItem
- Remove a definição não utilizada de ItemType em TodoList/TaskList
