### ISSUE TITLE
Fase 1 - Frontend: Implementar componente TaskForm com CSS

### ISSUE THREAD

**Issue by paulosalvatore** [SalvatoreAcademyEmpresa/gerenciamento-de-tarefas#9]
# Implementar componente TaskForm com CSS

## Descrição
Desenvolver o componente TaskForm em ReactJS para permitir a criação e edição de tarefas, incluindo a estilização com CSS.

## Tarefas
- [x] Criar o componente TaskForm
- [x] Implementar a lógica para criar e editar tarefas
- [x] Adicionar estilos CSS para o componente
- [x] Testar o formulário para garantir que a criação e edição de tarefas está funcionando corretamente

**Comment by alanrochagomes** [comment]
O componente TaskForm para adicionar novas tarefas:

- Implementa o componente TaskForm que recebe a função onAdd como prop
- Gerencia o estado para armazenar o novo todo digitado
- Adiciona função para adicionar novo todo à lista se não estiver vazio
- Limpa o campo de entrada de texto após adicionar a tarefa
- Renderiza campo de entrada de texto e botão para adicionar a tarefa
- Estiliza o layout do componente TaskForm
